# Generated by Django 4.2.2 on 2023-07-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
