# Generated by Django 4.2.2 on 2023-07-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otp_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(default=7072),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
