# Generated by Django 4.2.2 on 2023-06-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('desc', models.TextField(blank=True, max_length=1100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, max_length=1100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='')),
                ('title', models.TextField(max_length=1100)),
                ('slug', models.CharField(max_length=225, unique=True)),
                ('avalibale', models.SmallIntegerField()),
                ('have_unique_code', models.BooleanField(default=False)),
                ('unique_code', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
