# Generated by Django 4.2.2 on 2023-07-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='register_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
